OPTIONAL__command_defaults: {}
OPTIONAL__flow_config:
  REQUIRED__boundary_configs:
  - OPTIONAL__material_zones:
    - TYPE__int|str
    OPTIONAL__outside_zones:
    - TYPE__int|str
    REQUIRED__boundary_model:
      REQUIRED__kind: TYPE__str
      REQUIRED__params: {}
OPTIONAL__heat_flux_config:
  REQUIRED__boundary_configs:
  - OPTIONAL__material_zones:
    - TYPE__int|str
    OPTIONAL__outside_zones:
    - TYPE__int|str
    REQUIRED__boundary_model:
      REQUIRED__kind: TYPE__str
      REQUIRED__params: {}
OPTIONAL__hydrostat_config:
  OPTIONAL__sampling_model:
    REQUIRED__kind: TYPE__str
    REQUIRED__params: {}
  REQUIRED__interpolation_model:
    REQUIRED__kind: TYPE__str
    REQUIRED__params: {}
  REQUIRED__pressure_model:
    REQUIRED__kind: TYPE__str
    REQUIRED__params: {}
REQUIRED__files_config:
  OPTIONAL__flow: TYPE__Path
  OPTIONAL__heat_flux: TYPE__Path
  OPTIONAL__initial_conditions: TYPE__Path
  REQUIRED__area: cond_octree.area
  REQUIRED__check: cond_octree.chk
  REQUIRED__conductivity: cond_octree.cond
  REQUIRED__error: cond_octree.err
  REQUIRED__files: fehmn.files
  REQUIRED__final_conditions: cond_octree.fin
  REQUIRED__grid: cond_octree.fehm
  REQUIRED__history: cond_octree.hist
  REQUIRED__input: cond_octree.dat
  REQUIRED__material_zone: cond_octree_material.zone
  REQUIRED__output: cond_octree.out
  REQUIRED__outside_zone: cond_octree_outside.zone
  REQUIRED__permeability: cond_octree.perm
  REQUIRED__pore_pressure: cond_octree.ppor
  REQUIRED__rock_properties: cond_octree.rock
  REQUIRED__run_root: cond_octree
  REQUIRED__storage: cond_octree.stor
  REQUIRED__water_properties: cond_octree.wpi
REQUIRED__rock_properties_config:
  REQUIRED__compressibility_configs:
  - REQUIRED__property_model:
      REQUIRED__kind: TYPE__str
      REQUIRED__params: {}
    REQUIRED__zones:
    - TYPE__int|str
  REQUIRED__conductivity_configs:
  - REQUIRED__property_model:
      REQUIRED__kind: TYPE__str
      REQUIRED__params: {}
    REQUIRED__zones:
    - TYPE__int|str
  REQUIRED__grain_density_configs:
  - REQUIRED__property_model:
      REQUIRED__kind: TYPE__str
      REQUIRED__params: {}
    REQUIRED__zones:
    - TYPE__int|str
  REQUIRED__permeability_configs:
  - REQUIRED__property_model:
      REQUIRED__kind: TYPE__str
      REQUIRED__params: {}
    REQUIRED__zones:
    - TYPE__int|str
  REQUIRED__porosity_configs:
  - REQUIRED__property_model:
      REQUIRED__kind: TYPE__str
      REQUIRED__params: {}
    REQUIRED__zones:
    - TYPE__int|str
  REQUIRED__specific_heat_configs:
  - REQUIRED__property_model:
      REQUIRED__kind: TYPE__str
      REQUIRED__params: {}
    REQUIRED__zones:
    - TYPE__int|str
  REQUIRED__zone_assignment_order:
  - TYPE__int|str
